

-- Documento creado para almacenar la esturctura de base de datos a trabajar

CREATE TABLE IF NOT EXISTS pets(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50)NOT NULL CHECK (name <> ''),
    age integer NOT NULL,
    height integer NOT NULL,
    weight integer NOT NULL,
    race VARCHAR(50)NOT NULL CHECK (race <> ''),
    typeAnimal VARCHAR(15) NOT NULL CHECK (typeAnimal <> ''),
    petStatus VARCHAR(15) NOT NULL CHECK (petStatus <> '')
)

CREATE TABLE IF NOT EXISTS USERS
(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    avatar VARCHAR,
    name VARCHAR(80) NOT NULL,
    lastname VARCHAR(80) NOT NULL,
    numberphone VARCHAR(20) NOT NULL,
    status BOOLEAN DEFAULT true
);


CREATE TABLE IF NOT EXISTS CREDENTIALS
(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR UNIQUE NOT NULL,
    password VARCHAR NOT NULL,
    userid integer references USERS(id)
);

CREATE TABLE IF NOT EXISTS ROLES
(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(80)
);

INSERT INTO ROLES (NAME, description)
VALUES
('Dev', 'Hace referencia al desarrollador, para mantenimiento'),
('Admin', 'Hace referencia al administrador con funciones de moderador'),
('User', 'Hace referencia a un usuario comun')
